-- ARABLOW JSS ACADEMY - Supabase setup
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  full_name text not null,
  admission_no text not null unique,
  email text not null unique,
  class text not null default 'Grade 7',
  created_at timestamptz not null default now()
);

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  student_auth_id uuid references auth.users(id) on delete set null,
  admission_no text not null,
  student_name text,
  subject text not null,
  grade text not null,
  score integer not null,
  total_questions integer not null,
  percentage numeric(5,2) not null,
  answers jsonb,
  created_at timestamptz not null default now()
);

create index if not exists students_admission_no_idx on public.students(admission_no);
create index if not exists exam_results_student_auth_id_idx on public.exam_results(student_auth_id);

alter table public.students enable row level security;
alter table public.exam_results enable row level security;

drop policy if exists "Students can check admission number" on public.students;
create policy "Students can check admission number" on public.students for select to anon, authenticated using (true);

drop policy if exists "Students can register" on public.students;
create policy "Students can register" on public.students for insert to anon, authenticated with check (true);

drop policy if exists "Authenticated students can save results" on public.exam_results;
create policy "Authenticated students can save results" on public.exam_results for insert to authenticated with check (student_auth_id = (select auth.uid()));

drop policy if exists "Students can view their own results" on public.exam_results;
create policy "Students can view their own results" on public.exam_results for select to authenticated using (student_auth_id = (select auth.uid()));

grant select, insert on public.students to anon, authenticated;
grant select, insert on public.exam_results to authenticated;

-- STAFF / ADMIN PORTAL
create table if not exists public.admin_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text not null default 'Teacher',
  role text not null default 'teacher' check (role in ('teacher','admin')),
  created_at timestamptz not null default now()
);

alter table public.admin_profiles enable row level security;
drop policy if exists "Staff can view own admin profile" on public.admin_profiles;
create policy "Staff can view own admin profile" on public.admin_profiles
for select to authenticated using (auth_user_id = (select auth.uid()));
grant select on public.admin_profiles to authenticated;

drop policy if exists "Teachers can view students" on public.students;
create policy "Teachers can view students" on public.students
for select to authenticated using (exists (select 1 from public.admin_profiles ap where ap.auth_user_id = (select auth.uid())));

drop policy if exists "Teachers can view all results" on public.exam_results;
create policy "Teachers can view all results" on public.exam_results
for select to authenticated using (exists (select 1 from public.admin_profiles ap where ap.auth_user_id = (select auth.uid())));
